# Generated by Django 6.0.3 on 2026-04-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_brand_promocode_size_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommended_products',
            field=models.ManyToManyField(blank=True, to='shop.product', verbose_name='Рекомендуемые товары'),
        ),
    ]
